# Generated by Django 5.0 on 2024-01-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentApp', '0008_image_accommodation_alter_image_post_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
